// Economy simulator: plays the game with a greedy bot and prints a pacing
// report as Markdown.
//
//   dart run tool/simulate.dart [--minutes=180] [--out=docs/simulation_report.md]
//
// Two scenarios are played: one run without IPO (early pacing) and a long
// session where the bot goes public whenever that doubles its shares.
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:gpuempire/core/big_number.dart';
import 'package:gpuempire/core/economy_config.dart';
import 'package:gpuempire/core/economy_engine.dart';
import 'package:gpuempire/core/number_format.dart';
import 'package:gpuempire/core/quests.dart';
import 'package:gpuempire/core/simulator.dart';

/// The bot goes public when the IPO would at least double its shares.
const ipoFactor = 2.0;

void main(List<String> args) {
  var minutes = 180.0;
  String? out;
  for (final arg in args) {
    if (arg.startsWith('--minutes=')) {
      minutes = double.parse(arg.substring('--minutes='.length));
    } else if (arg.startsWith('--out=')) {
      out = arg.substring('--out='.length);
    }
  }

  final config = EconomyConfig.fromJson(
    jsonDecode(File('assets/config/economy.json').readAsStringSync())
        as Map<String, Object?>,
  );
  final engine = EconomyEngine(config);
  final book = QuestBook(
    engine,
    QuestBook.parse(
      jsonDecode(File('assets/config/quests.json').readAsStringSync())
          as Map<String, Object?>,
    ),
  );
  final firstRun = Simulator(engine, questBook: book).run(seconds: 45 * 60);
  final session = Simulator(
    engine,
    questBook: book,
    ipoFactor: ipoFactor,
  ).run(seconds: minutes * 60);
  final report = buildReport(config, firstRun, session);

  stdout.write(report);
  if (out != null) {
    File(out)
      ..createSync(recursive: true)
      ..writeAsStringSync(report);
  }
}

String buildReport(EconomyConfig config, SimResult first, SimResult session) {
  final b = StringBuffer()
    ..writeln('# Economy simulation report')
    ..writeln()
    ..writeln(
      'Greedy bot. Generated by `dart run tool/simulate.dart`. Scenario A: '
      'the first 45 minutes without IPO. Scenario B: '
      '${formatDuration(session.duration)} of play, going public whenever '
      'that at least doubles the shares held.',
    )
    ..writeln();

  final garage = config.locations.first;
  final startingLines = garage.lines.where((l) => l.startLevel > 0).length;

  b
    ..writeln('## Pacing targets')
    ..writeln()
    ..writeln('| Target | Goal | Result | |')
    ..writeln('|---|---|---|---|');
  final firstBuy = first.firstPurchase;
  _target(
    b,
    'First upgrade',
    '< 60s',
    firstBuy == null ? 'never' : formatDuration(firstBuy),
    firstBuy != null && firstBuy < 60,
  );
  final linesAt5 = first.linesUnlockedBy(300, startingLines);
  _target(b, 'Lines open at 5 min', '>= 3', '$linesAt5', linesAt5 >= 3);
  for (final minutes in [15, 30]) {
    final idle = first.longestIdle(0, minutes * 60.0);
    _target(
      b,
      'Longest "nothing to do", first $minutes min',
      '<= 3m',
      formatDuration(idle),
      idle <= 180,
    );
  }
  final infraShare = _infraSpent(garage, first, 900) / _spent(first, 900);
  b.writeln(
    '| Share of spending on power/cooling, first 15 min | 5-35% '
    '| ${(infraShare * 100).round()}% '
    '| ${infraShare >= 0.05 && infraShare <= 0.35 ? 'OK' : 'MISS'} |',
  );
  final move = session.firstTime(SimEventKind.move);
  _target(
    b,
    'Move to the 2nd location',
    '30-50 min',
    move == null ? 'never' : formatDuration(move),
    move != null && move >= 1800 && move <= 3000,
  );
  final ipo = session.firstTime(SimEventKind.ipo);
  _target(
    b,
    'First IPO (bot policy)',
    '60-90 min',
    ipo == null ? 'never' : formatDuration(ipo),
    ipo != null && ipo >= 3600 && ipo <= 5400,
  );
  b
    ..writeln()
    ..writeln(
      '"Nothing to do" = no affordable purchase that raises income by at '
      'least 1%.',
    );

  b
    ..writeln()
    ..writeln('## Scenario B: locations, IPOs and skills')
    ..writeln()
    ..writeln('| Event | Time |')
    ..writeln('|---|---|');
  for (final e in session.events) {
    final what = switch (e.kind) {
      SimEventKind.move => 'Moved to ${e.label}',
      SimEventKind.ipo => 'IPO: +${formatBig(BigNumber.parse(e.label))} shares',
      SimEventKind.skill => 'Skill: ${e.label}',
      _ => null,
    };
    if (what != null) b.writeln('| $what | ${formatDuration(e.time)} |');
  }

  b
    ..writeln()
    ..writeln('## Scenario A: line unlocks, managers and quests')
    ..writeln()
    ..writeln('| Event | Time |')
    ..writeln('|---|---|');
  for (final e in first.events) {
    final what = switch (e.kind) {
      SimEventKind.lineUnlocked => 'Line',
      SimEventKind.manager => 'Manager',
      SimEventKind.quest => 'Quest done',
      SimEventKind.move => 'Moved',
      _ => null,
    };
    if (what != null) {
      b.writeln('| $what: ${e.label} | ${formatDuration(e.time)} |');
    }
  }

  b
    ..writeln()
    ..writeln('## Scenario B: waiting, by time window')
    ..writeln()
    ..writeln(
      '| Window | Longest "nothing to do" | Longest gap between purchases | Purchases |',
    )
    ..writeln('|---|---|---|---|');
  const windows = [0, 5, 15, 30, 45, 60, 90, 120, 150, 180, 240];
  for (var i = 0; i + 1 < windows.length; i++) {
    final from = windows[i] * 60.0;
    final to = windows[i + 1] * 60.0;
    if (from >= session.duration - 1) break;
    final end = to < session.duration ? to : session.duration;
    final count = session.purchaseTimes
        .where((t) => t >= from && t < end)
        .length;
    b.writeln(
      '| ${windows[i]}-${windows[i + 1]} min '
      '| ${formatDuration(session.longestIdle(from, end))} '
      '| ${formatDuration(session.longestGap(from, end))} '
      '| $count |',
    );
  }

  b
    ..writeln()
    ..writeln('## Scenario B: snapshots')
    ..writeln()
    ..writeln(
      '| Time | Location | Cash | Income/s | Run earned | Shares held | IPO now '
      '| Speed | Line levels |',
    )
    ..writeln('|---|---|---|---|---|---|---|---|---|');
  for (final s in session.snapshots) {
    final minute = (s.time / 60).round();
    final isLast = identical(s, session.snapshots.last);
    if (minute % 10 != 0 && minute != 5 && !isLast) continue;
    b.writeln(
      '| ${formatDuration(s.time)} '
      '| ${config.locations[s.state.locationIndex].id} '
      '| \$${formatBig(s.state.cash)} '
      '| \$${formatBig(s.estimatedRate)} '
      '| \$${formatBig(s.state.totalEarned)} '
      '| ${formatBig(s.state.meta.shares)} '
      '| ${formatBig(s.shares)} '
      '| ${(s.efficiency * 100).round()}% '
      '| ${s.state.lines.map((l) => l.level).join(' / ')} |',
    );
  }
  return b.toString();
}

double _infraSpent(LocationConfig loc, SimResult r, double time) {
  double series(InfraConfig c, int levels) =>
      c.baseCost * (math.pow(c.costGrowth, levels) - 1) / (c.costGrowth - 1);
  final state = r.snapshots.lastWhere((s) => s.time <= time).state;
  return series(loc.power, state.powerLevel) +
      series(loc.cooling, state.coolingLevel);
}

double _spent(SimResult r, double time) => r.events
    .where((e) => e.time <= time)
    .fold(0.0, (sum, e) => sum + e.cost.toDouble());

void _target(StringBuffer b, String name, String goal, String got, bool ok) {
  b.writeln('| $name | $goal | $got | ${ok ? 'OK' : 'MISS'} |');
}
