// Economy simulator: plays the game with a greedy bot and prints a pacing
// report as Markdown.
//
//   dart run tool/simulate.dart [--minutes=90] [--out=docs/simulation_report.md]
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:gpuempire/core/economy_config.dart';
import 'package:gpuempire/core/economy_engine.dart';
import 'package:gpuempire/core/number_format.dart';
import 'package:gpuempire/core/simulator.dart';

void main(List<String> args) {
  var minutes = 90.0;
  String? out;
  for (final arg in args) {
    if (arg.startsWith('--minutes=')) {
      minutes = double.parse(arg.substring('--minutes='.length));
    } else if (arg.startsWith('--out=')) {
      out = arg.substring('--out='.length);
    }
  }

  final json = File('assets/config/economy.json').readAsStringSync();
  final config = EconomyConfig.fromJson(
    jsonDecode(json) as Map<String, Object?>,
  );
  final engine = EconomyEngine(config);
  final result = Simulator(engine).run(seconds: minutes * 60);
  final report = buildReport(config, result);

  stdout.write(report);
  if (out != null) {
    File(out)
      ..createSync(recursive: true)
      ..writeAsStringSync(report);
  }
}

String buildReport(EconomyConfig config, SimResult r) {
  final b = StringBuffer()
    ..writeln('# Economy simulation report')
    ..writeln()
    ..writeln(
      'Greedy bot, ${formatDuration(r.duration)} of active play. '
      'Generated by `dart run tool/simulate.dart`.',
    )
    ..writeln();

  final startingLines = config.lines.where((l) => l.startLevel > 0).length;

  b
    ..writeln('## Pacing targets')
    ..writeln()
    ..writeln('| Target | Goal | Result | |')
    ..writeln('|---|---|---|---|');
  final first = r.firstPurchase;
  _target(
    b,
    'First upgrade',
    '< 60s',
    first == null ? 'never' : formatDuration(first),
    first != null && first < 60,
  );
  final linesAt5 = r.linesUnlockedBy(300, startingLines);
  _target(b, 'Lines open at 5 min', '>= 3', '$linesAt5', linesAt5 >= 3);
  final infraShare = _infraSpent(config, r, 900) / _spent(r, 900);
  b.writeln(
    '| Share of spending on power/cooling, first 15 min | 10-35% '
    '| ${(infraShare * 100).round()}% '
    '| ${infraShare >= 0.10 && infraShare <= 0.35 ? 'OK' : 'MISS'} |',
  );
  for (final minutes in [15, 30]) {
    final idle = r.longestIdle(0, minutes * 60.0);
    _target(
      b,
      'Longest "nothing to do", first $minutes min',
      '<= 3m',
      formatDuration(idle),
      idle <= 180,
    );
  }
  b
    ..writeln()
    ..writeln(
      '"Nothing to do" = no affordable purchase that raises income by at '
      'least 1%.',
    );

  b
    ..writeln()
    ..writeln('## Line unlocks and managers')
    ..writeln()
    ..writeln('| Event | Time |')
    ..writeln('|---|---|');
  for (final e in r.events) {
    if (e.kind == SimEventKind.lineUnlocked || e.kind == SimEventKind.manager) {
      final what = e.kind == SimEventKind.manager ? 'Manager' : 'Line';
      b.writeln('| $what: ${e.label} | ${formatDuration(e.time)} |');
    }
  }

  b
    ..writeln()
    ..writeln('## Waiting, by time window')
    ..writeln()
    ..writeln(
      '| Window | Longest "nothing to do" | Longest gap between purchases | Purchases |',
    )
    ..writeln('|---|---|---|---|');
  const windows = [0, 5, 15, 30, 60, 90, 120, 180];
  for (var i = 0; i + 1 < windows.length; i++) {
    final from = windows[i] * 60.0;
    final to = windows[i + 1] * 60.0;
    if (from >= r.duration - 1) break;
    final count = r.purchaseTimes.where((t) => t >= from && t < to).length;
    final end = to < r.duration ? to : r.duration;
    b.writeln(
      '| ${windows[i]}-${windows[i + 1]} min '
      '| ${formatDuration(r.longestIdle(from, end))} '
      '| ${formatDuration(r.longestGap(from, end))} '
      '| $count |',
    );
  }

  b
    ..writeln()
    ..writeln('## Snapshots')
    ..writeln()
    ..writeln(
      '| Time | Cash | Income/s | Total earned | IPO shares | Speed '
      '| Power/Cooling lvl | Upgrades | Line levels |',
    )
    ..writeln('|---|---|---|---|---|---|---|---|---|');
  for (final s in r.snapshots) {
    final minute = (s.time / 60).round();
    final isLast = identical(s, r.snapshots.last);
    if (minute % 5 != 0 && minute != 1 && minute != 2 && !isLast) continue;
    b.writeln(
      '| ${formatDuration(s.time)} '
      '| \$${formatBig(s.state.cash)} '
      '| \$${formatBig(s.estimatedRate)} '
      '| \$${formatBig(s.state.totalEarned)} '
      '| ${formatBig(s.shares)} '
      '| ${(s.efficiency * 100).round()}% '
      '| ${s.state.powerLevel}/${s.state.coolingLevel} '
      '| ${s.state.upgrades.length} '
      '| ${s.state.lines.map((l) => l.level).join(' / ')} |',
    );
  }
  return b.toString();
}

double _infraSpent(EconomyConfig config, SimResult r, double time) {
  double series(InfraConfig c, int levels) =>
      c.baseCost * (math.pow(c.costGrowth, levels) - 1) / (c.costGrowth - 1);
  final state = r.snapshots.lastWhere((s) => s.time <= time).state;
  return series(config.power, state.powerLevel) +
      series(config.cooling, state.coolingLevel);
}

double _spent(SimResult r, double time) => r.events
    .where((e) => e.time <= time)
    .fold(0.0, (sum, e) => sum + e.cost.toDouble());

void _target(StringBuffer b, String name, String goal, String got, bool ok) {
  b.writeln('| $name | $goal | $got | ${ok ? 'OK' : 'MISS'} |');
}
