import 'big_number.dart';
import 'economy_engine.dart';
import 'game_state.dart';

/// What a quest asks the player to do.
enum QuestType {
  /// Complete [QuestConfig.amount] jobs by tapping.
  manualJobs,

  /// Get line [QuestConfig.target] to level [QuestConfig.amount].
  lineLevel,

  /// Get every line in the current location to level [QuestConfig.amount].
  allLinesLevel,

  /// Hire manager [QuestConfig.target].
  hireManager,

  /// Own [QuestConfig.amount] income upgrades.
  upgrades,

  /// Get infrastructure [QuestConfig.target] (`power` or `cooling`) to
  /// level [QuestConfig.amount].
  infraLevel,

  /// Earn [QuestConfig.amount] in total this run.
  totalEarned,

  /// Earn [QuestConfig.amount] in the current location.
  locationEarned,

  /// Arrive at location [QuestConfig.target].
  reachLocation,

  /// Go public [QuestConfig.amount] times.
  ipoCount,

  /// Own [QuestConfig.amount] investor skills.
  skills,
}

/// One quest. Story quests come from `assets/config/quests.json` and their
/// texts live in the translation files under the quest id; contracts are
/// generated by [ContractBook].
class QuestConfig {
  const QuestConfig({
    required this.id,
    required this.type,
    required this.amount,
    required this.rewardFraction,
    required this.minReward,
    this.target,
  });

  factory QuestConfig.fromJson(Map<String, Object?> json) => QuestConfig(
    id: json['id']! as String,
    type: QuestType.values.byName(json['type']! as String),
    target: json['target'] as String?,
    amount: (json['amount']! as num).toDouble(),
    rewardFraction: (json['rewardFraction']! as num).toDouble(),
    minReward: BigNumber.from(json['minReward']! as num),
  );

  final String id;
  final QuestType type;

  /// Line id, manager id, infrastructure kind or location id, depending on
  /// [type].
  final String? target;
  final double amount;

  /// The cash reward is this share of everything earned in the current
  /// location, so it keeps pace with the economy without snowballing...
  final double rewardFraction;

  /// ...but never less than this, so early rewards still feel good.
  final BigNumber minReward;
}

/// Progress towards a quest goal.
class QuestProgress {
  const QuestProgress(this.current, this.goal);

  final double current;
  final double goal;

  bool get isComplete => current >= goal;
  double get fraction => goal <= 0 ? 1 : (current / goal).clamp(0.0, 1.0);
}

/// Shared quest rules for story quests and contracts.
abstract class _QuestRules {
  const _QuestRules(this.engine);

  final EconomyEngine engine;

  /// Whether [q] can be worked on in the current location (a level quest
  /// for a line of another location cannot).
  bool isAvailableHere(GameState s, QuestConfig q) {
    final loc = engine.location(s);
    return switch (q.type) {
      QuestType.lineLevel => loc.hasLine(q.target!),
      QuestType.hireManager => loc.managers.any((m) => m.id == q.target),
      _ => true,
    };
  }

  QuestProgress progress(GameState s, QuestConfig q) {
    final loc = engine.location(s);
    final current = switch (q.type) {
      QuestType.manualJobs => s.manualJobs.toDouble(),
      QuestType.lineLevel =>
        loc.hasLine(q.target!)
            ? s.lines[loc.lineIndex(q.target!)].level.toDouble()
            : 0.0,
      QuestType.allLinesLevel =>
        s.lines.map((l) => l.level).reduce((a, b) => a < b ? a : b).toDouble(),
      QuestType.hireManager => s.managers.contains(q.target) ? 1.0 : 0.0,
      QuestType.upgrades => s.upgrades.length.toDouble(),
      QuestType.infraLevel =>
        engine.infraLevel(s, InfraKind.values.byName(q.target!)).toDouble(),
      QuestType.totalEarned => s.totalEarned.toDouble(),
      QuestType.locationEarned => s.locationEarned.toDouble(),
      QuestType.reachLocation => _locationProgress(s, q.target!),
      QuestType.ipoCount => s.meta.ipoCount.toDouble(),
      QuestType.skills => s.meta.skills.length.toDouble(),
    };
    final goal = switch (q.type) {
      QuestType.hireManager || QuestType.reachLocation => 1.0,
      _ => q.amount,
    };
    return QuestProgress(current, goal);
  }

  /// 1 once [locationId] is reached; on the way there, progress towards
  /// the current location's goal if it leads there next.
  double _locationProgress(GameState s, String locationId) {
    final index = engine.config.locations.indexWhere((l) => l.id == locationId);
    if (index <= s.locationIndex) return 1;
    if (index == s.locationIndex + 1) {
      // Capped below 1: the quest completes on arrival, not before.
      return engine.locationProgress(s).clamp(0.0, 0.99);
    }
    return 0;
  }

  /// Cash [q] pays right now: a share of what was earned in the current
  /// location, so a fresh location is not flooded with cash.
  BigNumber reward(GameState s, QuestConfig q) =>
      s.locationEarned.scale(q.rewardFraction).max(q.minReward);
}

/// Max's story quests: handed out one at a time, in order, once per save.
class QuestBook extends _QuestRules {
  const QuestBook(super.engine, this.quests);

  final List<QuestConfig> quests;

  static List<QuestConfig> parse(Map<String, Object?> json) =>
      (json['quests']! as List<Object?>)
          .cast<Map<String, Object?>>()
          .map(QuestConfig.fromJson)
          .toList();

  /// The active story quest, or null once all are done.
  QuestConfig? current(GameState s) =>
      s.meta.storyIndex < quests.length ? quests[s.meta.storyIndex] : null;

  /// Pays the active story quest (times [factor], e.g. after a rewarded ad)
  /// and moves on. Null if it is not complete.
  GameState? claim(GameState s, {double factor = 1}) {
    final q = current(s);
    if (q == null || !progress(s, q).isComplete) return null;
    final earned = s.earn(reward(s, q).scale(factor));
    return earned.copyWith(
      meta: earned.meta.copyWith(storyIndex: s.meta.storyIndex + 1),
    );
  }
}

/// Short generated quests that keep every run interesting once the story
/// quest is out of reach (e.g. it needs a location the player left).
class ContractBook extends _QuestRules {
  const ContractBook(super.engine);

  /// The issued contract, or a freshly generated one if none is stored yet
  /// (call [ensure] to store it).
  QuestConfig current(GameState s) {
    final stored = s.contract;
    if (stored != null) {
      return QuestConfig(
        id: 'contract_${s.contractIndex}',
        type: QuestType.values.byName(stored.type),
        target: stored.target,
        amount: stored.amount,
        rewardFraction: engine.config.contracts.rewardFraction,
        minReward: BigNumber.zero,
      );
    }
    return _generate(s);
  }

  /// Stores the current contract so its goal stays put while the player
  /// works on it.
  GameState ensure(GameState s) {
    if (s.contract != null) return s;
    final q = _generate(s);
    return s.copyWith(
      contract: ContractState(
        type: q.type.name,
        target: q.target,
        amount: q.amount,
      ),
    );
  }

  /// Alternates between levelling the weakest unlocked line and an
  /// earnings target for the current location.
  QuestConfig _generate(GameState s) {
    final c = engine.config.contracts;
    final loc = engine.location(s);
    final id = 'contract_${s.contractIndex}';
    if (s.contractIndex.isEven) {
      var weakest = 0;
      for (var i = 0; i < s.lines.length; i++) {
        if (s.lines[i].isUnlocked &&
            s.lines[i].level < s.lines[weakest].level) {
          weakest = i;
        }
      }
      final level = s.lines[weakest].level;
      final milestone = engine.nextMilestone(level)?.level;
      var target = level + c.levelStep;
      if (milestone != null && milestone - level >= c.levelStep) {
        target = milestone;
      }
      return QuestConfig(
        id: id,
        type: QuestType.lineLevel,
        target: loc.lines[weakest].id,
        amount: target.toDouble(),
        rewardFraction: c.rewardFraction,
        minReward: BigNumber.zero,
      );
    }
    // Earnings contract: double what this location has earned.
    // Capped so the stored double stays finite (JSON cannot hold Infinity).
    final goal = (s.locationEarned.scale(2))
        .max(BigNumber.from(1000))
        .min(BigNumber.from(1e300));
    return QuestConfig(
      id: id,
      type: QuestType.locationEarned,
      amount: goal.toDouble(),
      rewardFraction: c.rewardFraction,
      minReward: BigNumber.zero,
    );
  }

  GameState? claim(GameState s, QuestConfig contract, {double factor = 1}) {
    if (!progress(s, contract).isComplete) return null;
    return ensure(
      s
          .earn(reward(s, contract).scale(factor))
          .copyWith(contractIndex: s.contractIndex + 1, clearContract: true),
    );
  }
}

/// What Max shows: the story quest when it can be worked on here, else a
/// contract.
class QuestBoard {
  const QuestBoard(this.story, this.contracts);

  final QuestBook story;
  final ContractBook contracts;

  /// The quest on display and whether it is a contract.
  (QuestConfig, bool) active(GameState s) {
    final q = story.current(s);
    if (q != null && story.isAvailableHere(s, q)) return (q, false);
    return (contracts.current(s), true);
  }

  /// Stores the contract on display, if a contract is showing.
  GameState ensure(GameState s) => contracts.ensure(s);

  QuestProgress progress(GameState s, QuestConfig q) => story.progress(s, q);

  BigNumber reward(GameState s, QuestConfig q) => story.reward(s, q);

  /// Claims the displayed quest. Null if it is not complete.
  GameState? claim(GameState s, {double factor = 1}) {
    final (quest, isContract) = active(s);
    return isContract
        ? contracts.claim(s, quest, factor: factor)
        : story.claim(s, factor: factor);
  }
}
